//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildDefinition()
        {
            this.BuildInstances = new HashSet<BuildInstance>();
        }
    
        public int BuildDefinitionId { get; set; }
        public string BuildDefinitionName { get; set; }
        public string VersionName { get; set; }
        public string ResultsPath { get; set; }
        public string ResultsShare { get; set; }
        public string BuildDefinitionPattern { get; set; }
    
        public virtual TiaVersion TiaVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildInstance> BuildInstances { get; set; }
    }
}
