//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuildInstance()
        {
            this.TestReports = new HashSet<TestReport>();
            this.ReportAssemblies = new HashSet<ReportAssembly>();
            this.ReportFixtures = new HashSet<ReportFixture>();
        }
    
        public int BuildInstanceId { get; set; }
        public string BuildInstanceName { get; set; }
        public int BuildDefinitionId { get; set; }
        public string DateId { get; set; }
    
        public virtual BuildDefinition BuildDefinition { get; set; }
        public virtual TestDate TestDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestReport> TestReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAssembly> ReportAssemblies { get; set; }
        public virtual ReportBuildInstance ReportBuildInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFixture> ReportFixtures { get; set; }
    }
}
