//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbRef
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReport
    {
        public int ReportId { get; set; }
        public int BuildInstanceId { get; set; }
        public string MachineName { get; set; }
        public bool Success { get; set; }
        public bool Executed { get; set; }
        public int Time { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public int TestcaseId { get; set; }
    
        public virtual BuildInstance BuildInstance { get; set; }
        public virtual Testcase Testcase { get; set; }
    }
}
